### ISSUE TITLE
Simulate commands

### ISSUE THREAD

**Issue by dheeraj1997** [dheeraj1997/microprocessor-simulator#3]
Simulate commands for micro processor like-
ADD - add integer to register
ADR - add register to another register
DCR - decrease value of register by 1
INR - increase value of register by 1
MOV - mov value of register to another register
RST - reset value to 0 of a register
SET - set value of a register

**Comment by dheeraj010497** [comment]
Picking up

**Comment by dheeraj1997** [comment]
#4 addresses this

**Comment by dheeraj1997** [comment]
#5 completes this issue
